statkraft/shyft

shyft/tests/netcdf/calibration.yaml
shyft/tests/netcdf/configuration.yaml
shyft/tests/netcdf/datasets.yaml
shyft/tests/netcdf/region.yaml
shyft/tests/test_netcdf.py

This is a test update to use the Atnsjoen dataset instead of the previous one that we want to delete.  After this is merged, we can proceed with a *deep* removal of next files in the shyft-data repo:
https://github.com/statkraft/shyft-data/blob/master/netcdf/orchestration-testdata/cell_info.nc
https://github.com/statkraft/shyft-data/blob/master/netcdf/orchestration-testdata/stations_discharge.nc
https://github.com/statkraft/shyft-data/blob/master/netcdf/orchestration-testdata/stations_met.nc
By deep removal I mean removing the above files in the git history too.  For this, I suggest to use [this tool](https://rtyley.github.io/bfg-repo-cleaner/).  After this PR would be accepted, I will open a ticket in shyft-data so as to remember doing this.

Tests for Atnsjoen dataset

---

shyft/orchestration/simulator.py
shyft/repository/netcdf/geo_ts_repository.py
shyft/tests/demo_statkraft_stuff.py
shyft/tests/test_simple_simulator.py

This PR slightly cleans and promotes @yisak's code for adjusting the Kirchner q state variable for instant discharge by measured discharge. It also adds two tests to check that the code works as expected.

Shyft 29 Promote code for adjusting q with observed discharge

---

shyft/repository/netcdf/__init__.py
shyft/repository/netcdf/region_model_repository.py
shyft/tests/netcdf/atnsjoen_region_bad.yaml
shyft/tests/test_netcdf_region_model_repository.py

This is a work in progress PR for improvements that @sigbjorn asked in the [gitter channel](https://gitter.im/statkraft).  Open to comments here.

Several improvements for checking that YAML files are sane

---

shyft/orchestration/configuration/yaml_configs.py
shyft/repository/interpolation_parameter_repository.py
shyft/repository/netcdf/cf_region_model_repository.py
shyft/tests/netcdf/neanidelva_interpolation.yaml
shyft/tests/netcdf/neanidelva_model.yaml
shyft/tests/netcdf/neanidelva_region.yaml
shyft/tests/netcdf/neanidelva_simulation.yaml

Changes in orchestration to use separate configuration file for interpolation parameters. The interpolation parameters for each source type are to be explicitly specified in the configuration file.

Configuration for interpolation parameters.

---

.gitignore
api/api.vcxproj
api/python/api.python.vcxproj
api/python/pt_gs_k.python.vcxproj
api/python/pt_hs_k.python.vcxproj
api/python/pt_ss_k.python.vcxproj
core/bayesian_kriging.h
core/core.vcxproj
test/test.vcxproj

Building shyft for Windows from scratch.
Uncovered missing references and library paths.

Windows build fixes

---

shyft/orchestration/configuration/yaml_configs.py
shyft/orchestration/configuration/yaml_constructors.py
shyft/repository/netcdf/cf_geo_ts_repository.py
shyft/repository/netcdf/erainterim_data_repository.py

Enabling consistent repository construction for configuration-based orchestration. The consistency is maintained across all repositories except service-based repositories used internally at Statkraft.

Consistent repository construction

---

shyft/orchestration/configuration/yaml_configs.py
shyft/orchestration/configuration/yaml_constructors.py
shyft/orchestration/simulator.py
shyft/orchestration/simulators/config_simulator.py
shyft/repository/generated_state_repository.py
shyft/repository/geo_ts_repository_collection.py
shyft/repository/netcdf/cf_region_model_repository.py
shyft/repository/netcdf/erainterim_data_repository.py
shyft/tests/netcdf/neanidelva_calibration.yaml
shyft/tests/netcdf/neanidelva_datasets.yaml
shyft/tests/netcdf/neanidelva_interpolation.yaml
shyft/tests/netcdf/neanidelva_model.yaml
shyft/tests/netcdf/neanidelva_simulation.yaml

This PR introduces the following :
- Added the functionality to explicitly select the source types which are to be fetched from each repo in a geo_ts_repo_collection
- Added a method to ConfigCalibrator for saving optimized parameters to model YAML file.
- Added a state repository which can be initialized during configuration (before RegionModel construction) and which can be extended to generate initial states from user-specified initial values.
- Enabled calls to methods of ConfigSimulator and ConfigCalibrator with info defined in configuration as defaults.
- Adapted orchestration to latest changes in api

Enhance orchestration

---

shyft/orchestration/configuration/yaml_configs.py
shyft/orchestration/simulators/config_simulator.py
shyft/repository/netcdf/arome_data_repository.py

This PR introduces classes for orchestrating configuration-based real-time forecast runs.

Orchestrating real-time forecast runs

---

shyft/orchestration/configuration/yaml_constructors.py
shyft/repository/generated_state_repository.py
shyft/repository/netcdf/cf_region_model_repository.py
shyft/repository/service/gis_region_model_repository.py

This PR adds the following functionalities:
- Overriding default state with user-specified values
- Setting catchment level parameters

Catchment level parameters and mock state

---

shyft/orchestration/configuration/yaml_constructors.py

Updated yaml based region_model_repository constructor to handle caching of geo_data.

Updates to region-model repository constructor to handle caching of geo_data

---

core/pt_gs_k.h
core/pt_hs_k.h
core/pt_ss_k.h
shyft/.idea/misc.xml
shyft/.idea/shyft.iml
shyft/tests/test_simple_simulator.py

actual evap and potential evap had wrong unit-conversion, now corrected to mm/h as stated by document string.

Fix conversion from mm/s to mm/h

---

shyft/orchestration/configuration/yaml_configs.py

This PR introduces the following changes:
- Added start_datetime override while creating YAMLSimConfig inside YAMLForecastConfig for real-time runs

Added start_datetime override while creating YAMLSimConfig

---

shyft/orchestration/simulators/config_simulator.py
shyft/repository/netcdf/cf_region_model_repository.py
shyft/repository/service/gis_region_model_repository.py

Removed mapping of catchment ID to 0-based index in orchestration.

Catch index to ID

---

shyft/orchestration/configuration/yaml_configs.py
shyft/orchestration/simulator.py
shyft/orchestration/simulators/config_simulator.py
shyft/tests/test_statkraft_run.py

Overview
* separation of configuration and simulators
Ensure that user deal with directly with the shyft api once created through orchestration class.
This is to avoid that the user find same data 'several places'.
Now the config is used to construct the objects, and the objects provides real access to shyft.api core 
* simplification

Enhance orchestration2

---

shyft/orchestration/simulator.py
shyft/orchestration/simulators/config_simulator.py

This PR introduces a fix whcih enables copying of ConfigSimulator. The copy constructor referred to an attribute which had been removed from the class.

Made ConfigSimulator copyable.

---

shyft/repository/netcdf/arome_data_repository.py
shyft/repository/service/gis_location_service.py
shyft/tests/test_ssa_geo_ts_repository.py

Added calculation of elevation from surface_geopotential in Arome repo.
Changed station identification attribute from OBJECTID to GIS_ID gis_location_service.

Gis id arome repo

---

shyft/repository/netcdf/arome_concat_data_repository.py
shyft/repository/netcdf/ec_concat_data_repository.py
shyft/tests/api/tests.api.pyproj

Added repositories for fetching multiple forecasts and concatenating forecasts to generate continuous time series.

Arome and EC concat repo

---

api/api.h
api/boostpython/api_region_environment.cpp
api/boostpython/api_time_series.cpp
shyft/api/__init__.py
shyft/tests/api/test_region_model_stacks.py
shyft/tests/api/test_time_series.py

This PR is just a minor extensions that allows fast access to values at specified time for TsVector and any GeoPointSourceVector (Temperature,Precipitation,RelHum,WindSpeed,Radiation).
Functions are exposed to python, and tests added to verify the exposure and illustrate the usage.
Some documentation-strings are also updated to improve the overall documentation and maintenance of it.

TsVector and GeoPointSource with .values_at_time(t) function

---

shyft/repository/netcdf/arome_concat_data_repository.py
shyft/repository/netcdf/arome_data_repository.py
shyft/repository/netcdf/cf_geo_ts_repository.py
shyft/repository/netcdf/cf_region_model_repository.py
shyft/repository/netcdf/cf_ts_repository.py
shyft/repository/netcdf/ec_concat_data_repository.py
shyft/repository/netcdf/erainterim_data_repository.py

#Overview
Improve repository handling, including env. variable

Repo enhance

---

shyft/repository/service/gis_location_service.py
shyft/repository/service/gis_region_model_repository.py
shyft/tests/test_gis_region_model_repository.py

Added sub_service as an option to __init__, to pull data from the right service.
Column names are different between the two services, which I for now handle by several "if peru_service:".

Modified GisLocationService to handle Peru

---

shyft/orchestration/simulators/config_simulator.py

Quick fix using github directly, may want to run through tests.

fix of save_calibrated_state per #368

---

shyft/repository/netcdf/utils.py
shyft/repository/netcdf/wx_repository.py

This PR improves the `WXParallelizationRepository`

Parallelization fix
