statkraft/shyft

- shyft/__init__.py
- shyft/orchestration2/base_config.py
- shyft/orchestration2/generic/region.py
- shyft/orchestration2/netcdf/region.py
- shyft/orchestration2/netcdf/source_dataset.py
- shyft/orchestration2/netcdf/target.py
- shyft/orchestration2/utils.py
- shyft/tests/netcdf/calibration.yaml
- shyft/tests/netcdf/datasets.yaml
- shyft/tests/netcdf/region.yaml
Uses new location of datafiles for orchestration2 testing in '../shyft-data'.
Also, this honors a new `SHYFTDATA` environment variable for telling where the `shyft-data` local repository is located.   If not found, it defaults to '../shyft-data'.
This should be ready for merging.
> Shyft data handling

- core/utctime_utilities.h
- test/test.cbp
- test/utctime_utilities_test.cpp
- test/utctime_utilities_test.h
Its not the exact truth, it is still possible to pass 'invalid' calendar coordinates
but this helps for those passing dates like 2001.13.44  etc.
> implemented exception for unreasonable calendar coordinates

- shyft/orchestration2/calibrator.py
- shyft/orchestration2/shyft_runner.py
Simple fix: Saving of calibration results using orchestration2 should work now.
> fixing calibration result saving in orchestration2.

- .travis.yml
- CMakeLists.txt
- README.md
- cmake/DownloadAndExtractTarball.cmake
- core/CMakeLists.txt
- shyft/api/CMakeLists.txt
- test/CMakeLists.txt
Here it is another PR for CMake support.  This time the support has been ported to Python 3 (no support for Python2 is here).  Although cmake seems to work just fine in my local box, I am still having problems with TravisCI of this style:
```
kirchner_test.cpp:(.text+0x1d4f): undefined reference to `CxxTest::TestTracker::tracker()'
kirchner_test.cpp:(.text+0x1d9b): undefined reference to `CxxTest::TestTracker::tracker()'
kirchner_test.cpp:(.text+0x1de7): undefined reference to `CxxTest::TestTracker::tracker()'
kirchner_test.cpp:(.text+0x1e28): undefined reference to `CxxTest::TestTracker::tracker()'
CMakeFiles/test_shyft.dir/kirchner_test.cpp.o: In function `kirchner_test::test_solve_from_zero_q()':
kirchner_test.cpp:(.text+0x2126): undefined reference to `CxxTest::TestTracker::tracker()' …
```
> Support for CMake (ported to Python 3)

- README.md
- build_api_cmake.sh
- setup.py
This is refinement to use cmake in setup.py when on a Linux platform.  This fixes the setup.py that is not currently able to build SHyFT in any platform (even on Linux).  The dependencies have been  specified more clearly in the README.md file.
This is meant to be merged asap.
> setup.py uses cmake on Linux for building SHyFT

- shyft/repository/netcdf/arome_data_repository.py
- shyft/repository/netcdf/time_conversion.py
- shyft/tests/api/test_calendar_and_time.py
- shyft/tests/api/test_time_axis.py
- shyft/tests/test_arome_respository.py
- shyft/tests/test_geo_ts_repository_collection.py
- shyft/tests/test_netcdftime.py
- shyft/tests/test_simple_simulator.py
- shyft/tests/tests.pyproj
We  (Yisak and myself) made this minor change to add handling of CF compliant netcdf-time.
During the work we used pycharm, and the shyft pycharm project, testing out features in pycharm to drive the test-driven development process. It worked nice!
Now we require netcdf/arome file to provide CF compliant time description.
We support only trivial calendar/steps, seconds, minutes, hours, days as a starting point.
We use  t_utc[i] = t_origin + delta_t* t_netcdf[i], in np. array form hoping for great performance.
We deliberately avoid converting a number (linear time) to calendar-coordinate (aka datetime) and back to number (linear time), for performance and robustness reasons.
> Netcdftime

- requirements.txt
swig is a requirement, but it is not installable from PyPI, so this PR removes it from requirements.txt.  The TravisCI build script does not require this (conda is used instead), so this PR is not breaking it.
> Removed swig in requirements.txt as it is not in the PyPI repo

- api/python/__init__.i
- api/python/pt_gs_k.i
- api/python/pt_hs_k.i
- api/python/pt_ss_k.i
- core/gamma_snow.h
- core/pt_gs_k.h
- shyft/tests/api/test_region_model_stacks.py
- test/gamma_snow_test.cpp
- test/gamma_snow_test.h
- test/test.cbp
A minor change to gamma_snow:
effective_snow_cv  ::= snow_cv + snow_cv_forest_factor* forest_fraction + snow_cv_altitude_factor*cell_altitude.
All parameters defaults to 0.0, so it is 100% backward compatible, no changes needed.
To enable feature, set the gs.*_cv_factors to the value you want, and the snow_cv is adjusted according to the cell altitude and| or forest-fraction.
Note: ensure that you get the snow_cv you want by testing for forest_fraction 0.0..1.0, and altitudes 0.. max elevation in your cell model.
> GammaSnow: added snow_cv sensitive to forest and altitude 

- api/python/__init__.i
- core/utctime_utilities.cpp
- core/utctime_utilities.h
- shyft/repository/yaml_state_repository.py
- shyft/tests/api/test_calendar_and_time.py
- test/test.cbp
- test/utctime_utilities_test.cpp
- test/utctime_utilities_test.h
The utctime and calendar library now supports timezone and DST.
The changes are backward compatible, and **the only difference from previous version** is that the to_string() methods now returns ISO8601 formatted strings. The formatting can be further extended utilizing python built-in libraries later.
e.g: Previous utc : 2015.02.03T12:30:00 now gives tz indicator  2015-02-03T12:30:00Z
This includes _calendar semantics_ for the .add(), .diff_units() and .trim() methods.
Briefly this means that adding a calendar day to a time, could mean adding 23,24 or 25 hours if the calendar observes dst. For details on the python side, ref. to test in test_calendar_and_time.py.
One example to illustrate it:
`
def test_calendar_add_during_dst(self):
osl = api.Calendar("Europe/Oslo")
t0 = osl.time(2016, …
> Timezone and DST support for utctime and calendar library

- shyft/repository/service/gis_region_model_repository.py
- shyft/tests/demo_statkraft_stuff.py
Changes to CatchmentFetcher in Statkraft's gis_region_model_repo to enable using SUBCATCH_ID as subcatchment identifier.
> Changes to CatchmentFetcher in Statkraft's gis_region_model_repo

- api/boostpython/api_interpolation.cpp
- core/inverse_distance.h
- shyft/.idea/misc.xml
- shyft/.idea/shyft.iml
- shyft/tests/api/test_region_model_stacks.py
As Yisak poinited out, the constructor and attribute of the IDW precipitation parameters did not match.
This is now fixed, and documentation added accordingly.
The constructor now takes scale_factor, -as is the property of the parameter also.
The formula is
adj.precipitation := precipitation * (scale_factor) ^ ( delta_z_in_meters/100.0)
Added test to verify the default is scale_factor = 1.02.
> IDW precipitation.scale_factor cleaned up and documented

- shyft/.idea/misc.xml
- shyft/.idea/shyft.iml
- shyft/orchestration/simulator.py
- shyft/repository/netcdf/region_model_repository.py
- shyft/repository/service/gis_region_model_repository.py
- shyft/repository/service/ssa_geo_ts_repository.py
- shyft/tests/api/test_region_model_stacks.py
- shyft/tests/test_gis_region_model_repository.py
- shyft/tests/test_simple_simulator.py
- shyft/tests/test_ssa_geo_ts_repository.py
We try this simple approach first:
… let the repository provide a .clone method if special copy-semantics that preserve repository specific model info is really needed (yes it is, like the shape-information when reading from GIS system)
Later we can see if we are able to sort out other mechanisms (or just by explicit modelling) ways of dealing with repository-specific information related to models.
From the SHyFT core perspective, (the computational), this is irrelevant information, but from the presentation/admin/orchestration point of view, quite useful.
One possible solution is to make this split explicit by design:
like 
shyft_model:
contains a core_model (like PTGSK etc, this is the stuff we would like to copy-clone)
self.other_stuff (like the geo-shape/mapping info etc., this is the …
> first version of approach to solve issue with tear-off model-copy. 

- core/pt_gs_k.h
- core/pt_hs_k.h
- core/pt_ss_k.h
- shyft/tests/api/test_calibration_types.py
This enable the alpha and albedo factor of priestley taylor to be calibrated.
pt_xx_k stacks now allow 2 more parameters for calibration.
> calibration: add priestley taylor parameter 

- api/api.vcxproj
- api/python/api.python.vcxproj
- api/python/pt_gs_k.python.vcxproj
- api/python/pt_hs_k.python.vcxproj
- api/python/pt_ss_k.python.vcxproj
- core/core.vcxproj
- test/test.vcxproj
Use environment variable SHYFT_DEPENDENCIES to point to the path
where dependencies are located on Windows.
> Win64 dependencies

- api/boostpython/pt_hs_k.cpp
- api/boostpython/pt_ss_k.cpp
- core/pt_gs_k.h
- core/pt_hs_k.h
- core/pt_ss_k.h
The parameter names for pt_xx_k (xx= gs, hs, ss) is now gs,hs,ss respectively for the snow routines.
The parameter.get_name(i) is now equal to the class attribute syntax, e.g. 
pt_hs_k.parameter.hs.tx is now "hs.tx"
> Calibration parameter names for pt_xx_k is now xx.parameter name

- shyft/repository/netcdf/erainterim_data_repository.py
This PR changes the ERAInterimDataRepository by removing the time-sorting needed for unsorted datasets.
The time dimension in the dataset of the netcdf file generated from ERA-Interim comes unsorted. The ERAInterimDataRepository took account of this during data extraction by initially sorting the arrays for each variable. Even if the time period for which data is to be extracted is short, the whole array has to be sorted to extract the correct period. This sorting takes time for large netcdf datasets. The alternative of picking (selecting) the correct time without sorting creates significantly more overhead when extracting variables which require deaccumulation. The option which is fastest and very cheap is to sort the whole dataset during saving from ERAInterim. The repository does not …
> ERAInterimDataRepository now handles only time-sorted datasets.

- shyft/repository/service/gis_region_model_repository.py
This PR fixes a bug in repository/service/gis_region_model_repository.py which assigns wrong elevation values to cells.
> Fixed bug which assigns wrong elevation values to cells.

- shyft/orchestration/simulators/config_simulator.py
This PR introduces a control on the the existence of all catch IDs for all target timeseries used in calibration. Instead of skipping the target timeseries for which not all IDs are found in the region model, an error is raised with info on which IDs are not found.
> Added control on whether all catch IDs for all target ts exist.

- core/time_axis.h
- core/utctime_utilities.cpp
- core/utctime_utilities.h
- shyft/tests/api/test_calendar_and_time.py
- test/utctime_utilities_test.cpp
Extended calendar/time-axis functionality and handling of dst to cover 
timestep > 1h < 1 day.
Previously, dls support only for  >= day timesteps.
> extended dls support to cover resolution >1h < 1 day

- api/api.h
- api/boostpython/api_actual_evapotranspiration.cpp
- api/boostpython/api_time_series.cpp
- api/boostpython/expose.h
- shyft/.idea/misc.xml
- shyft/.idea/shyft.iml
- shyft/api/__init__.py
- shyft/repository/service/gis_region_model_repository.py
- shyft/tests/api/test_region_model_stacks.py
- shyft/tests/api/test_time_series.py
- shyft/tests/test_geo_data_serialization.py
- test/api_test.cpp
- test/api_test.h
- test/test.cbp
**Background**
Fetching and computing accurate  geo-cell data from the GIS system takes resources and time compared to running SHyFT models. For larger models, with a high degree of accuracy, 
this involves millions of polygons describing forrest, lakes, reservoirs and glaciers.
Added togehter, this takes in the order of several seconds (20-200).
GIS-system data is rather constant for a model, so we add caching-support to this level so that models can be retrieved in split-seconds.
The additional code goes in two parts (c++ and python)
1. the cell-vector at core/api level  provides methods for serializing to/from suitable format for persistence
2. the affected repository uses the mechanism above plus some few lines to 
check for existence of the cached data before retrieving from the GIS …
> Enable caching of GIS geo_cell_data for SHyFT models

- api/boostpython/api_actual_evapotranspiration.cpp
- core/actual_evapotranspiration.h
- core/pt_gs_k.h
- core/pt_hs_k.h
- core/pt_ss_k.h
- test/actual_evapotranspiration_test.cpp
This fix resolves issue reported when running SHyFT at timestep different from hour, like 3hour.
1. The actual evapotranspiration is now calculated as
input_potential_evap * ( 1- exp(-3.0* kirchner.state.q/ae_scale_factor))* (1-snow_covered_area)
So given snow_covered_area=0.0, and kirchner.state.q = scale_factor, the ae is 0.95* pe
2. The unit in the response time-series is mm/h for potential and actual evapotranspiration.
> actual evapotranspiration fix so that is independent of timestep

- .travis.yml
- core/geo_cell_data.h
- core/model_calibration.h
- core/region_model.h
This PR internalize the previousely 0-based catchment-identifers (cids), so that the user can use cids that relates to external identities.
Internally SHyFT are still using internal 0-based cids for performance reasons.
There are no changes externally, except for the relaxed requirement to cids that now can be any integer.
Another PR related to simplifying the python parts (cid-map to internal-id map) will be submitted later.
> Catchment Identifiers

- shyft/repository/netcdf/cf_region_model_repository.py
Two improvements for the netcdf repository are suggested:
- Bug-fix: api.LandTypeFractions() requires as last argument an unknown_fraction, which was so far set to 0. However, this unknown fraction must be calculated from the known fractions, otherwise land type fractions are computed wrongly.
- Faster construction of cell vector using "create_from_geo_cell_data_vector(...)" method.
> Fractions fix

- shyft/orchestration/configuration/yaml_constructors.py
- shyft/repository/service/gis_location_service.py
- shyft/repository/service/gis_region_model_repository.py
- shyft/tests/test_gis_region_model_repository.py
This PR inculdes the following:
- Automatic switching of gis service server from PROD to PREPROD
- Usage of server names as parameters to GIS related classes and handling of this in yaml based configuration and orchestration
- Fix to a test for gis_region_model_repo caused by mismatch between bounding-box and catchment location
> Gis server switch

- core/pt_gs_k.h
- shyft/tests/api/test_calibration_types.py
pt_gs_k was lacking 3 parameters, for the get(i) get_name(i) and set(v) related to gamma snow.
To ease orchestration and repositories, these are now available for getting/setting etc. so that the parameter yaml files can have the complete parameter configuration that have an impact on the calculated result.
The extra parameters are:
"gs.initial_bare_ground_fraction":double
"gs.winter_end_day_of_year" : int, default 100
"gs.calculate_iso_pot_energy": bool (0.0 or 1.0)
The api does automatic conversion from internal types to external number/float representation, so that setting parameters by vector do give the expected result.
Notice that we do not do any range-check/sanity check when setting parameters. This is entirely up to the repository/user to perform at the perimeter (when reading …
> Extend parameter list

- api/boostpython/api_priestley_taylor.cpp
- api/boostpython/api_skaugen.cpp
- api/boostpython/expose.h
- core/core.vcxproj.filters
- core/model_calibration.h
- core/region_model.h
- shyft/tests/api/test_region_model_stacks.py
- test/cell_builder_test.cpp
- test/hbv_tank_test.cpp
This PR resolves issue:
#98 
by providing the script-user a more fine-grained control over the region_model run as well as calibration and parameter optimization process.
The test/demo python scripts are updated accordingly, to touch/use the new functions.
We also will provide updated notebooks to illustrate the new functionality as soon as this is part of the master branch.
As per usual, each method and property mentioned do have doc-strings where we at best effort describe functionality and purpose.
**RegionModel changes**
A more fine-grained control of running the region-model is provided by splitting the run_interpolation() function into two parts:
`.initialize_cell_environment(time_axis)`
that prepares the cell.environment time-series with the supplied time-axis, and
fills in 0 for …
> Enhance shyft core api to ease scripting

- shyft/orchestration/simulators/config_simulator.py
This PR fixes a bug which assigned the wrong time_axis for a forecast run. The bug was introduced after the changes which removed the time_axis as a settable attribute of ConfigSimulator.
> Fixed a bug in assigning a time_axis while running a forecast.

- shyft/repository/netcdf/arome_data_repository.py
Changed regex for filename pattern of AROME to handle both the old and new filenaming. The change in name pattern resulted in the wrong file being picked (i.e. the latest availabe file with the old naming convention.)
> Arome namepattern fix

- SHyFT.sln
- api/api.vcxproj
- api/python/api.python.vcxproj
- api/python/hbv_stack.python.vcxproj
- api/python/pt_gs_k.python.vcxproj
- api/python/pt_hs_k.python.vcxproj
- api/python/pt_ss_k.python.vcxproj
- api/timeseries.h
- core/bayesian_kriging.h
- core/core.vcxproj
- core/inverse_distance.h
- core/time_axis.h
- core/timeseries.h
- shyft/orchestration/config.py
- shyft/tests/test_config_simulator.py
- shyft/tests/test_geo_data_serialization.py
- shyft/tests/test_opendap_repository.py
- test/inverse_distance_test.cpp
- test/test.vcxproj
The purpose of this PR is to shorten down the ci-test time.
A failure in getting time-coordinate to utc-time right also caused
missing data into the btk-routine, giving seg-fault. We prefer runtime-errors/exceptions,
so both cases are now fixed.
Most of shyft also runs without gdal, -for some service-based repositories we use gdal for processing geo-data, - this pr. encapsulates the use of gdal so that all relevant test can be run, even with missing gdal (still a problem on windows and python 3.5 at this moment, no prob on linux :-) )
> Test idw speedup

- api/boostpython/api_time_axis.cpp
- shyft/repository/interfaces.py
- shyft/repository/netcdf/cf_ts_repository.py
- shyft/repository/netcdf/geo_ts_repository.py
- shyft/repository/netcdf/opendap_data_repository.py
- shyft/tests/api/test_time_axis.py
- shyft/tests/test_netcdf_geo_ts_repository.py
- shyft/tests/test_opendap_repository.py
During testing notebooks, and running through the regression tests, it turned out that some parts failed, and it was due to lack of data-inputs. 
Looking into the root-cause it was discovered that repositories where using a time-filter algorithm that did exclude endpoints in the range that contained data needed to cover the request period.
These PR fixes this issues, cover it up with tests, and also ensures that notebooks with netcdf data succeeds running the demonstration scripts.
Also everywhere we do have datetime, ensure to use correct handling of calendar coordinates (y,m,d,h,m,s) utilizing the shyft.api.Calendar object to do the proper conversion to utctime (seconds since 1970.01.01 utc).
> Reading time-series from any repository should cover request period

- shyft/orchestration/simulators/config_simulator.py
Fixes issue #115 
At the same time, there is also an update of the  .yaml files for the shyft-doc neanidelv notebook.
In the yaml-based ConfigSimulator, we require the calibration parameter set into the yaml files to be fully specified. This is to ensure complete and consistent parameter-sets during calibration.
The code correctly reports that the there are parameters missing, including names, - the new parameters provided by the new routing functionality.
Users are required to add this to their existing yaml calibration parameter files, like listed below.
routing.velocity:
min: 0.0
max: 0.0
routing.alpha:
min: 0.9
max: 0.9
routing.beta:
min: 3.0
max: 3.0
Ref. to shyft-doc/noteboks/neanidelv example for details.
> add routing to known calibration parameter mapings

- core/gamma_snow.h
- test/gamma_snow_test.cpp
- test/test.vcxproj.user
The problem was related to gamma-snow, and the use of corr_lwc function. It caused the pt_gs_k stack to throw run-time error in some trivial cases.
It turned  out that in certain cases, the function was called with b1, or b2 zero, and sometimes z1 or z2 was zero.
In either cases, it did not find a solution, very reasonable for the case of b2 zero, as it gives nan, but failed to find a reasonable solution for other cases (ending up in exceeding number of iterations).
This PR try to fix this by adressing the root causes, - the parameters passed to the routine, and then using standard boost minimima finder to solve the problem.
We will check&verify this solution by doing some more real-life tests at Statkraft, ensuring that Ok solutions are found.
> gamma snow and corr_lwc issues

- api/boostpython/api_kalman.cpp
- core/kalman.h
- shyft/api/__init__.py
- shyft/tests/api/test_kalman.py
- test/kalman_test.cpp
- test/kalman_test.h
To support grid pre-prosessing utlizing grid-forecasts and observations in historical time,
we have added another function that computes the running-bias prediction,
given 
1. merged-forecast-ts (typically projected from surrounding grid-point to observation-point)
2. observation-ts, like temperature observed for the same historical period
3. the wanted time-axis for the bias-ts (typically the historical period, 3h resolution from 1.9...)
4. the usual kalman parameters, as well as initial state if it exists.
returns
bias_ts, as forecasted at the beginning of each day through the complete period.
note: the first day uses current state of the bias-predictor, so if not set, the bias-predicted will contains 0.0 the first day.
After some days, the bias-ts will resemble the kalman bias …
> Added compute_running_bias to kalman predictor

- core/cell_model.h
- shyft/api/__init__.py
- shyft/tests/api/test_time_series.py
- test/cell_builder_test.cpp
- test/test.vcxproj.user
region_model.statistics.sum/average cell_feature could return empty results in cases where the first cell of the cellvector was not part of the cell that was subject to simulation (calculation_filter), and the time-axis of that cell was empty (typical initial state).
This issue was experienced by Eli, ref. issue 109:
#109   where the same functions returned no values after calibration.
The issue was only related to extracting those time-series to python in that way, -any other method, including direct access would work.
In addition this PR also add some minor feature to ease working more seamlessly with the core-time-series (TsFixed and TsPoint in python) and the full feature TimeSeries class.
This is done by providing .TimeSeries property, that returns the core time-series …
> fixed issue with rm.statistics.results when using calculation_filter 

- api/boostpython/expose.h
- api/boostpython/hbv_stack.cpp
- api/boostpython/pt_gs_k.cpp
- api/boostpython/pt_hs_k.cpp
- api/boostpython/pt_ss_k.cpp
- shyft/api/hbv_stack/__init__.py
- shyft/api/pt_gs_k/__init__.py
- shyft/api/pt_hs_k/__init__.py
- shyft/api/pt_ss_k/__init__.py
- shyft/tests/api/test_region_model_stacks.py
When working and calibrating models, it's nice to work with the fully instrumented models that allows the end user to inspect all possible aspects of the model.
During calibration/optimization, Shyft have template specialized model that optimize away both waste of memory and computational efforts. This way we get the highest possible speed during calibration.
To ease switchiing from a full model and a tuned optimized model, there is now a special clone method on the full-model that creates a tuned model clone.
The tuned opt-model clone is exactly equal to its full model, except:
* results (they are not needed, soon to be overwritten during calibration)
* catchment-specific parameters are omitted ( calibration require only one region-parameter, applied to the catchment-ids of interest)
* …
> Make parameter optimisation easier

- api/boostpython/expose.h
- api/boostpython/hbv_stack.cpp
- api/boostpython/pt_gs_k.cpp
- api/boostpython/pt_hs_k.cpp
- api/boostpython/pt_ss_k.cpp
- shyft/api/hbv_stack/__init__.py
- shyft/api/pt_gs_k/__init__.py
- shyft/api/pt_hs_k/__init__.py
- shyft/api/pt_ss_k/__init__.py
Added complementary functions for cloning an opt-model to a full-model.
Useful in the context of working with opt-models, then switch to full-model for inspecting details.
> Added convert to full-model method and function

- api/api.h
- api/boostpython/api_target_specification.cpp
- api/boostpython/expose_statistics.h
- core/hbv_stack.h
- core/hbv_stack_cell_model.h
- core/model_calibration.h
- core/pt_gs_k.h
- core/pt_gs_k_cell_model.h
- core/pt_hs_k.h
- core/pt_hs_k_cell_model.h
- core/pt_ss_k.h
- core/pt_ss_k_cell_model.h
- core/region_model.h
- core/timeseries.h
- shyft/tests/api/test_calibration_types.py
- shyft/tests/api/test_region_model_stacks.py
- test/api_test.cpp
- test/calibration_test.cpp
- test/cell_builder_test.cpp
- test/region_model_test.cpp
- test/routing_test.cpp
- test/serialization_test.cpp
- test/test.vcxproj.user
- test/time_axis_test.cpp
- test/timeseries_test.cpp
- test/utctime_utilities_test.cpp
This PR adds cell charge speed [m^3/s] to the standard response of all model stacks.
The purpose is to ease study how a cell charges water, in snow-layer, or any other vertical layer of the cell.
This also enable calibration to take the yearly(or other period) hydrological balance, the accumulated cell charge should then typically be close to target-timeseries, typically set to zero.
Timeaxis in these cases would typically be 1 (one) step for a year.
For calibration a new goal-function is introduced,
ABS_DIFF - that computes the accumulated sum of fabs(target-simulated) over the time-axis specified
and to specify cell charge
```python
from shyft import api as s
t = s.TargetSpecificationPts()
t.calc_mode = s.ABS_DIFF
t.catchment_property = s.CELL_CHARGE
sum_charge = …
```
> Cell charge_m3s speed and calibration supporting hydrological yearly balance

- api/boostpython/api_time_axis.cpp
- core/time_axis.h
- core/utctime_utilities.h
- shyft/api/__init__.py
- shyft/tests/api/test_time_axis.py
added:
*  TimeAxis.time_points -> numpy array of time-points (useful for plot/chart/conversions)
*  somewhat more debug friendly time-axis str representation
fixed:
* exposure of TimeAxis.calendar_dt.calendar so that it works regardless access-paths
> Time points

- shyft/orchestration/simulators/config_simulator.py
There is a key error when writing calibration results of an hbv-stack calibration to yaml files. The reason is a mixup of mapping arguments. The suggested solution should work - I tested it with an HBV version of the shyft-doc notebooks.
However, there is sth one should be aware - and this probably needs to be fixed to my understanding:
The parameters of actual evaportanspiration of the pt_gs_k stack and of the hbv stack both map to "ae" (see e.g. api.hbv_stack.HbvParameter.ae). This can lead to false mapping, when using the mapping backward, as done in [here](https://github.com/statkraft/shyft/blob/master/shyft/orchestration/simulators/config_simulator.py#L168). In the shown example, the key "ae" is thus used twice in the dictionary, where it should be unique.
This can lead to a false …
> fixing mapping of hbv parameters when writing optimized parameters to yaml file after calibration

- core/cell_model.h
- shyft/tests/api/test_region_model_stacks.py
Setting state_collection(-1,False) on a model could for some cases cause segmentation fault.
This fixes the issues, plus adds tests that detect the issue before the fix.
> fixing state collect issue as reported by Yisak

- core/cell_model.h
- test/region_model_test.cpp
- test/test.vcxproj.user
This PR fixes correct start-time on the 
result-time-axis time-series when doing multiple re-runs, with same time-axis size, but different start-times on one model.
> fixes re-run time-axis

- CMakeLists.txt
armadillo version 7.800.1 is needed.
> step up dependency versions for armadillo

- shyft/repository/netcdf/arome_concat_data_repository.py
Provided by Yisak, the arome-concat repository with selection criteria 
on forecast-starting time.
This allow the repository to filter out the wanted forecast directly, based on supplied criteria.
> Forecast repository with start-time boundary conditions

- core/hbv_stack.h
- core/pt_gs_k.h
- core/pt_hs_k.h
- core/pt_ss_k.h
- shyft/tests/api/test_region_model_stacks.py
- shyft/tests/test_config_simulator.py
- test/pt_gs_k_test.cpp
- test/test.cbp
According to observations,  only precipitation that goes into non-covered lake/reservoir contributes directly to observed/measured inflow. (Little or no direct response is observed during winter-time.)
In periods with no snow-covered areas, the response is exactly as before, the precipitation that goes into reservoir/lakes gives a direct response (unless routed through river-network that is available).
During periods where we have snow covered area, only the uncovered lake/reservoir areas gives a direct response, the other part is routed through kirchner or (hbv)tank routine, so a more smooth response should be expected during these times.
There is no change in the interfaces, although we could have introduced yet another parameter to control this behavior directly.  (Could be another PR …
> Precipitation direct response only for lake/reservoir areas not covered by snow

- api/api_serialization.cpp
- api/boostpython/api_time_series.cpp
- api/timeseries.cpp
- api/timeseries.h
- shyft/tests/api/test_dtss.py
- shyft/tests/api/test_time_series.py
- test/timeseries_test.cpp
This is a minor functional extension, adding 
TimeSeries.integral(ta:TimeAxis)->TimeSeries member function and
corresponding free api function:
integral(ts:TimeSeries,ta:TimeAxis)->TimeSeries 
Usage and tests included in python tests-suite:
```python
def test_integral(self):
c = api.Calendar()
t0 = c.time(2016, 1, 1)
dt = api.deltahours(1)
n = 240
ta = api.TimeAxis(t0, dt, n)
fill_value = 1.0
ts = api.TimeSeries(ta=ta, fill_value=fill_value, point_fx=api.point_interpretation_policy.POINT_AVERAGE_VALUE)
ts_i1 = ts.integral(ta)
ts_i2 = api.integral(ts,ta)
ts_i1_values = ts_i1.values
for i in range(n):
expected_value = dt*fill_value
self.assertAlmostEqual(expected_value,ts_i1.value(i),4,"expect integral of each interval")
self.assertAlmostEqual(expected_value,ts_i2.value(i),4,"expect …
```
> Integral of time-series function

- api/api.cbp
- api/api.cpp
- api/boostpython/boostpython.cbp
- api/time_series.cpp
- api/time_series.h
- core/core.cbp
- core/dtss.h
- core/time_series_statistics.h
- test/test.cbp
- test/time_series_test.cpp
This PR contains internal computational improvements to the dtss functionality,
giving speedups 5x..10x depending on context.
The PR also contains a minor change to the percentile function that now supports nan in the
source ts's. They are simply filtered out, giving fewer members that goes into the
percentile calculation. Future extensions here includes ability to specify what to
do when encountering nan's, -like ignore, or set result to nan. (context/application specific).
For linux/codeblocks, we switch to putting precompiled headers into destination directories.
This solves the problem when you switch between debug/release build (the gch is invalid for one of them). However, you need to remove the .gch files generated from previous builds of codeblocks.
With the new settings, the PCH …
> Improve  and utilize multi-core performance, percentiles with nan support

- core/kalman.h
- shyft/tests/api/test_kalman.py
- test/kalman_test.cpp
Updated kalman filter to reflect paper Homleid, 2 may 1995)
* Initial values for ratio_W_V and calulation of W
* Computation for next state changed according to paper
Tests update accordingly, notebook with more examples, including noise suppression.
> Kalman Filter update

- api/api_serialization.cpp
- api/boostpython/api_dtss.cpp
- api/boostpython/api_kalman.cpp
- api/boostpython/api_time_series.cpp
- api/time_series.cpp
- api/time_series.h
- core/dtss.h
- shyft/api/__init__.py
- shyft/tests/api/test_time_series.py
- test/time_series_test.cpp
This PR adds mathematical operations on the existing TsVector class.
Practical use has proven that this feature will increase speed, and allow building on abstraction(expressions, vector of expressions), and avoid deflating into numpy-arrays to early.
E.g.:
```python
a= TsVector()
b= TsVector()
:  # add some time-series to a and b here
c = TimeSeries(...)  # ts  vs. vector is also supported
ta = TimeAxis(...) # some time-axis
d = (a*b + c)*3.5  # a x b is vector x vector,  + c is vector + ts, ()*3.5 is vector x scalar
p = d.percentiles(ta,stat_spec)   # as usual vector supports percentiles
d_avg = d.average(ta)  # applies average to all ts in d-vector
d_sft  = d.time_shift(deltahours(24))   #  time-shift all time-series in d by 24h
d_acc = d.accumulate(ta)  #  generate the accumulate …
```
> Time-series vector operations support

- api/api.vcxproj
- api/boostpython/api_time_series.cpp
- api/boostpython/boostpython.cbp
- api/boostpython/expose.h
- api/python/api.python.vcxproj
- api/python/hbv_stack.python.vcxproj
- api/python/pt_gs_k.python.vcxproj
- api/python/pt_hs_k.python.vcxproj
- api/python/pt_ss_k.python.vcxproj
- api/time_series.cpp
- api/time_series.h
- core/cell_model.h
- core/core.vcxproj
- core/region_model.h
- core/time_series.h
- shyft/tests/api/test_time_series.py
- test/cell_builder_test.cpp
- test/dtss_test.cpp
- test/serialization_test.cpp
- test/test.cbp
- test/test.vcxproj
- test/time_series_test.cpp
The interpolation step, when using the btk method throws exception if there are to few non-nan neighbors to produce the needed non-singular matrixes for computation.
In practical operation, this often occurs at the end of the forecast-period, e.g. EC forecasts,
in these circumstance, we want the run to continue and produce results as long as possible.
It is acceptable that the model produces nan's at the trailing parts of the computations.
During initialization/preparation of the region-model, the fill-values into the results, and the cell.environment is set to nan (formerly 0.0), to ease detection of this situation as well as for consistency and common sense.
The default behavior is best_effort, since the IDW algoritms was already best-effort.
For the sake of possible backward issues, …
> Best effort run

- shyft/orchestration/configuration/dict_configs.py
- shyft/repository/netcdf/cf_geo_ts_repository.py
- shyft/repository/netcdf/cf_region_model_repository.py
Modified the example CFRegionModelRepository to enable instantiation with dictionaries OR yaml config objects.
> Dict config in CFRegionModelRepository

- core/time_series_qm.h
#Overview 
using  ensure time-series that could have different time-resolution from the target time-axis for quantile mapping
> fix for fc time-resolution in quantile mapping

- shyft/repository/netcdf/concat_data_repository.py
When fetching forecasts with criterion 'forecasts_that_cover_period', the current repo is unable to return a forecast that starts exactly at t_run, and has a length equal to the requested utc_period (v_shift_first == v_shift_last)
This PR includes the end time in the slice boundary, and a forecast which is "perfectly aligned" with t_run and utc_period will be returned.
> Minor change in ConcatDataRepository
